local monarch = require "monarch.monarch"
local GlobalState = require "game.game_logic.global_state"

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "level")

	GlobalState:loadSave()
end

function on_message(self, message_id, message, sender)
	if message_id == hash("level") then
		monarch.show(hash("level"), { clear = true })
	elseif message_id == hash("win") then
		monarch.show(hash("win"), { clear = true })
	end
end
